title: AI in Math Seminar
description: AI in Math Seminar page

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima  # or your preferred theme

# Kramdown settings for math
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# MathJax settings
mathjax: true
